- stage: DockerPush
displayName: 📦 Build & Push Docker
dependsOn: Build
jobs:
  - job: docker
    displayName: Build and Push Image
    steps:
      # Ancienne version (à supprimer) :
-          - task: Docker@2
-            displayName: Build and Push to ACR
-            inputs:
-              command: buildAndPush
-              repository: '$(ACR_LOGIN_SERVER)/$(IMAGE_NAME)'
-              dockerfile: '**/Dockerfile'
-              azureSubscription: 'uami-managed-identity'`nazureazureSubscription: 'uami-managed-identity'`nazureContainerRegistry: '$(ACR_NAME)'
-              tags: |
-                latest

      # Nouvelle version :
+          - task: Docker@2
+            displayName: Build and Push to ACR
+            inputs:
+              command: buildAndPush
+              azureSubscription: 'uami-managed-identity'
+              azureazureSubscription: 'uami-managed-identity'`nazureazureSubscription: 'uami-managed-identity'`nazureContainerRegistry: '$(ACR_NAME)'
+              repository: '$(IMAGE_NAME)'
+              dockerfile: '**/Dockerfile'
+              tags: |
+                latest
