# ──────────────────────────────────────────────────────────────
# Pipeline CI – springweb (Spring Boot + Thymeleaf)
# ──────────────────────────────────────────────────────────────
trigger:
  branches:
    include:
      - main

pool:
  name: Default        # agent self-hosted MyLocalAgent

steps:
  - script: .\gradlew.bat clean build --no-daemon
    displayName: 'Build and Test'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/build/test-results/**/*.xml'
      failTaskOnFailedTests: true
