- stage: Build
  displayName: '🛠️ Build & Test'
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: JavaToolInstaller@0
        displayName: 'Install Java 17'
        inputs:
          versionSpec: '17'
          jdkArchitectureOption: 'x64'

      # Option A: cross-platform script
      - script: |
          chmod +x ./gradlew
          ./gradlew clean test --no-daemon
        displayName: 'Run Gradle build & tests'

      # Option B: use the Gradle task instead
      #- task: Gradle@2
      #  displayName: 'Build & Test with Gradle'
      #  inputs:
      #    gradleWrapperFile: 'gradlew'
      #    tasks: 'clean test'
      #    options: '--no-daemon'
