- stage: DockerPush
  displayName: '📦 Build & Push Docker'
  dependsOn: Build
  jobs:
  - job: Docker
    displayName: 'Build and Push image to ACR'
    steps:
-      - task: Docker@2
-        displayName: 'Build & Push to ACR'
-        inputs:
-          command: buildAndPush
-          azureSubscription: 'uami-managed-identity'
-          azureContainerRegistry: '$(ACR_NAME)'
-          repository: '$(IMAGE_NAME)'
-          dockerfile: '**/Dockerfile'
-          tags: |
-            latest
+      - script: |
+          # Se connecter à l’ACR via Managed Identity
+          az login --identity
+          # Construire l’image
+          docker build -f Dockerfile -t $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):latest .
+          # Pusher dans l’ACR
+          az acr login --name $(ACR_NAME)
+          docker push $(ACR_LOGIN_SERVER)/$(IMAGE_NAME):latest
+        displayName: 'Build & Push Docker via CLI'
