name: CD – Deploy to Azure Web App

on:
  workflow_run:
    workflows: ["CI & Publish to ACR"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      RG: rg-charityapp
      APP: web-charityapp
      ACR_LOGIN: acrcharityapp.azurecr.io
      IMAGE_NAME: springweb:${{ github.event.workflow_run.head_sha }}
      DB_URL: jdbc:mysql://mysqlaci.westeurope.azurecontainer.io:3306/charitydb?useSSL=false&serverTimezone=UTC

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (via publish profile)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          images: ${{ env.ACR_LOGIN }}/${{ env.IMAGE_NAME }}

      - name: Configure App Settings
        run: |
          az webapp config appsettings set \
            --name $APP \
            --resource-group $RG \
            --settings \
              SPRING_DATASOURCE_URL="$DB_URL" \
              SPRING_DATASOURCE_USERNAME="azureuser" \
              SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}"

      - name: Restart Web App
        run: az webapp restart --name $APP --resource-group $RG

      - name: Stream startup logs
        run: az webapp log tail --name $APP --resource-group $RG --timeout 60
